name: flutter_blogclup
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter
    dotted_border: ^2.0.0-nullsafety.0
    cupertino_icons: ^1.0.6
    flutter_svg: ^2.1.0
    smooth_page_indicator: ^1.2.1
    http: ^1.4.0
    flutter_launcher_icons: ^0.14.4


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    build_runner:
    flutter_gen_runner:

flutter:
    uses-material-design: true

    assets:
        - assets/img/icons/
        - assets/img/posts/large/
        - assets/img/posts/small/
        - assets/img/stories/
        - assets/img/background/

    fonts:
        - family: Avenir
          fonts:
              - asset: assets/fonts/AvenirLTProBook.otf
                weight: 200
              - asset: assets/fonts/AvenirLTProRoman.otf
                weight: 300
              - asset: assets/fonts/AvenirLTProMedium.otf
                weight: 400
              - asset: assets/fonts/AvenirLTProHeavy.otf
                weight: 700

flutter_gen:
    integrations:
        flutter_svg: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icons/virtual-reality.png"